### ISSUE TITLE
Information Page Stylizing

### ISSUE THREAD

**Issue by KaelanWillauer** [Open-Acidification/TankControllerManager#72]
The information page displays a readout of the current tank as a json string.
![image](https://user-images.githubusercontent.com/49886320/172071744-45a5a31b-7b41-4572-a22e-f0cbf527b512.png)
Although this gets the job done, it would be better to add some formatting.
1. Create an Information model that maps from the information string.
https://app.quicktype.io/
2. Use a UI widget like the divider class to format the page.
https://api.flutter.dev/flutter/material/Divider-class.html

**Comment by je-foster** [comment]
Fixed by #76.
